### ISSUE TITLE
Add season class

### ISSUE THREAD

**Issue by ChrisJones687** [ncsu-landscape-dynamics/PoPS#10]
Add season class for seasonality and make season class work even if selected season start month is later than end month (e.g. November to May)

**Comment by wenzeslaus** [comment]
I can add it since I already put it to the GRASS module.

https://github.com/ncsu-landscape-dynamics/r.spread.pest/blob/master/main.cpp#L108

Should I put it to master or to some other branch?

**Comment by ChrisJones687** [comment]
Thanks! I would add it to the Release branch and then we can release that branch to master when we are ready to have the official release version 1.0.0! I realized it was in both of the r version and grass version and seemed unnecessary to copy the code into each interface.

**Comment by ChrisJones687** [comment]
Added to Release branch!
