### ISSUE TITLE
Missing instructions where to fix bugs

### ISSUE THREAD

**Issue by wenzeslaus** [ncsu-landscape-dynamics/PoPS#14]
We miss instructions for core developers on where to put fixes. master? development (now 11 commits behind master)? fix/... branch (from what)? pull request (against what)?

Example, I have the fix for #13, but it is not clear where to put it.

Relates to #2 (originally meant for external contributors).

**Comment by ChrisJones687** [comment]
Added contributing guidelines and links other documents including the style guide @wenzeslaus made. Let me know if this makes sense and then I can close it.

**Comment by wenzeslaus** [comment]
The contributing file should be in the root whether or not it includes the style guide. I think any of these files (including CoD) are expected to be in the root of the source tree alongside README.
