### ISSUE TITLE
Generic code for dispersal kernels

### ISSUE THREAD

**Issue by wenzeslaus** [ncsu-landscape-dynamics/PoPS#19]
Wrap all dispersal kernel code into a generic API (function or class) so that no complexity of dispersal kernel code is in the `Simulation` itself, but instead, it is handled separately and a customizable way. This should remove all (or most) of the parameters related to kernels from the `Simulation.disperse()` function resulting in simpler Simulation calls and possible higher customization of kernels.

However, the possibility to modify kernel parameters during the simulation will be preserved because the whole kernel function/object can be replaced or modified when calling the `Simulation.disperse()` function.

**Comment by ChrisJones687** [comment]
### **Kernels to implement ([comes from data on seed dispersal but very applicable](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/1365-2745.12666)) :**
**Available in C++:**
Exponential: single parameter should be 1/(mean distance (this is calculated in MCMC))
Gamma: double parameter (shape (1.0) and scale(estimated))
Cauchy: double parameter (shift (0.0) and scale(estimated))
Weibull: double parameter (shape (1.0) and scale (estimated))
Normal: double Parameter (mean (0.0) and sd (estimated))
Lognormal: double parameter (mean (0.0) and sd (estimated))

**Not Available in standard C++:**
Available in [boost C++ math library](https://www.boost.org/doc/libs/1_68_0/boost/math/distributions.hpp)
WALD or Inverse Gaussian:
Logistic distribution:

Others to be implemented:
2Dt:
Power Law (Cauchy is one variant of a power law):
log hyperbolic secant:
Exponential Power:

**Comment by wenzeslaus** [comment]
Implemented in #27.
