### ISSUE TITLE
resolution should be double not int

### ISSUE THREAD

**Issue by petrasovaa** [ncsu-landscape-dynamics/PoPS#26]
https://github.com/ncsu-landscape-dynamics/PoPS/blob/master/simulation.hpp#L128

or am I missing something?

**Comment by wenzeslaus** [comment]
Yes, that's right. I assume this did not cause any problems since resolutions are usually integers. This will be fixed in the new dispersal kernel code (this piece is moving out of simulation and the type is already fixed in my local copy). PR will come soon.
